%%{init: {"theme": "base", "themeCSS": ".messageText{paint-order:stroke fill;stroke:#ffffff;stroke-width:5px;stroke-linejoin:round;fill:#111111!important;font-weight:600}.noteText{paint-order:stroke fill;stroke:#ffffff;stroke-width:3px;stroke-linejoin:round}"}}%%
sequenceDiagram
	autonumber

	actor Player as プレイヤー

	box NINTENDO 64 Nintendo Classics
		participant Emurator as エミュレーター
		participant Game as N64ゲーム
		participant VirtualData as 仮保存データ<br>(ゲーム内セーブ)
	end

	box Switch本体
		participant SwitchData as 本体セーブデータ
	end

	Note over Player,SwitchData: Nintendo64がクラッシュ
	Note over Game,VirtualData: ゲーム実行状態と<br>仮保存データが消失

	Note over SwitchData: 次回起動時は<br>前回起動時のデータ
